### ISSUE TITLE
Add Survey: Cannot scroll up or down after selecting a question

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#26]
Steps to replicate:
1. Login as admin.
2. Go to add survey form.
3. Click the core question link to expand the list.
4. Add a new element (question).
5. Try to scroll up or down.

Actual result: Page can't be scrolled up or down. Thus, the save as final, save as draft and cancel buttons cannot be clicked.

Expected result: User should be able to scroll up or down the page.

![image](https://cloud.githubusercontent.com/assets/7791554/6499676/a09479d6-c33a-11e4-8951-3ee0885e8d56.png)

**Comment by mgeronimo** [comment]
Ms. Shiela, I found a fix on it. I haven't pushed it yet though since there would be changes in the flow and I would like to ask you first if that change would be just fine.

The changes:
The modal will not close unless Close button was clicked. Questions can still be added continuously though even if the modal was not closed and reloaded. 

How the flow will be:
1. Click Add Element
2. Modal will appear
3. Select question
4. Click Add Question (the question will be added but the modal will not close)
5. Select another question to be added and click Add Question (the question will be added but the modal will not close)
6. If done selecting, click Close to close the modal.

Would this be fine or should we just stick on how it was before? Thanks!

**Comment by barbacenasmc** [comment]
Hi Ms. Madi,

Thanks for asking.  But wouldn't it be simpler if we use checkboxes instead
of radio buttons? Then,  instead of having two buttons, - Close and Add
Question,  let's make it Done. So when the user clicked it,  the modal will
then close. If the user clicked the add element button again under the
same,  the modal will display again but will still show the previously
selected items still checked.  But if the user already added another
header, the modal will show all items unchecked. What do you think about
this?

Hope this helps.

Thanks,
Shiela

**Comment by mgeronimo** [comment]
That would be nice. I will consult Sir Greg about it. Anyway, I'll just commit a fix on this for now. Thanks!

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
