### ISSUE TITLE
Add Site: List of province displays no option

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#74]
Steps to replicate:
1. Navigate to manage data page.
2. Click "Add" button and select "New Site".
3. On the add site form, select a region.
4. Click the province field to display the list of options

Actual result: List of province displays no option
Expected result: List of province should display options

![image](https://cloud.githubusercontent.com/assets/7791554/6632518/90011ec4-c972-11e4-9ebe-16da9f09dedd.png)

**Comment by mgeronimo** [comment]
This has already been resolved. Please check.

**Comment by xytram** [comment]
I think the issue is that when a region or any dynamic select field is selected, it takes a while before the next select field is populated. If you're selecting fast enough and tried to select something on the next field, It would return an empty list. If you waited at least 1.5 seconds, the list would already be populated.

So, I think the proper fix here is to add a delay or a loading icon before the select field is enabled or shown.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
